[mypy]
python_version = 3.11
strict = true
warn_unreachable = true
warn_unused_ignores = true
show_error_codes = true
files = src

[mypy-ebooklib.*]
ignore_missing_imports = true

[mypy-bs4.*]
ignore_missing_imports = true
